# Generated by Django 5.0.4 on 2024-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_email_elementdb_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('categorypic', models.ImageField(blank=True, null=True, upload_to='list Images')),
            ],
        ),
    ]
