# Generated by Django 5.0.4 on 2024-05-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_listdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementdb',
            old_name='category',
            new_name='Category',
        ),
    ]
