# Generated by Django 5.0.4 on 2024-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registerdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
